baseURL = "https://zhilin-C-zhou.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Zhilin Zhou"
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.footer]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.footer]]
URL = "resume"
name = "Resume"
weight = 2
[[menu.footer]]
URL = "note"
name = "Notes"
weight = "4"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "resume"
name = "Resume"
weight = 2
[[menu.main]]
URL = "note"
name = "Notes"
weight = "4"
[params]
author = "Zhilin Zhou"
contact_form_action = ""
description = ""
email = "z374zhou@uwaterloo.ca"
google_analitycs_id = ""
location = ""
logo = "images/signature.png"
mobile = ""
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = false
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-github-outline"
link = "#"
